/* tslint:disable */
/* eslint-disable */
/**
 * Releaser
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IReleaseFull
 */
export interface IReleaseFull {
    /**
     * 
     * @type {string}
     * @memberof IReleaseFull
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IReleaseFull
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof IReleaseFull
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IReleaseFull
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IReleaseFull
     */
    tags?: Array<string>;
}

export function IReleaseFullFromJSON(json: any): IReleaseFull {
    return IReleaseFullFromJSONTyped(json, false);
}

export function IReleaseFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): IReleaseFull {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'authorId': json['authorId'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function IReleaseFullToJSON(value?: IReleaseFull | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'authorId': value.authorId,
        'name': value.name,
        'description': value.description,
        'tags': value.tags,
    };
}


