/* tslint:disable */
/* eslint-disable */
/**
 * Releaser
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IRelease
 */
export interface IRelease {
    /**
     * 
     * @type {string}
     * @memberof IRelease
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IRelease
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IRelease
     */
    tags: Array<string>;
}

export function IReleaseFromJSON(json: any): IRelease {
    return IReleaseFromJSONTyped(json, false);
}

export function IReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IRelease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'tags': json['tags'],
    };
}

export function IReleaseToJSON(value?: IRelease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'tags': value.tags,
    };
}


